config/routes.rb
Rails.application.routes.draw do

  root 'welcome#homepage'
  
  get '/login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update]
  resources :books, only: [:index, :show]
  # resources :authors, only: [:index, :show]
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]

  get '/reading_list', to: 'users#reading_list'
  post '/add_to_reading_list/:id', to: 'books#add_to_reading_list'
  delete '/remove_from_reading_list/:id', to: 'books#remove_from_reading_list'

  get '/search', to: 'books#search'
  post '/add_to_reading_list_via_api', to: 'books#add_to_reading_list_via_api'
  delete '/remove_from_reading_list_via_api', to: 'books#remove_from_reading_list_via_api'
  delete '/remove_from_reading_list', to: 'books#remove_from_reading_list'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :reading_lists
    has_many :reviews
    has_many :books, through: :reading_lists

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :email_address, presence: true
    validates :email_address, uniqueness: true
    validates :password, presence: true

    def total_books
        self.books.count
    end

    def book_exist(title, author)
        self.books.find do |book|
            book.title == title && book.author.name == author
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :current_user, except: [:new, :create]
    before_action :find_user, only: [:edit, :update]

    def new
        @user = User.new
    end

    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:errors] = user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit  
        @user = @current_user
    end

    def update
        @user.update(user_params)
        @user.save
        flash[:notices] = ["User updated"]
        redirect_to edit_user_path(@user)
    end

    def reading_list
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email_address, :password, :password_confirmation)
    end

    def find_user
        @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_reading_list.html.erb
<h1 class="small-caps text-center">my reading list</h1>

<br>
<% if @current_user.books.count == 0 %>
    <p class="text-center">
        <em>You have no books saved on your reading list yet. Why not find your next favourite read in the <%= link_to "Library", books_path %>?</em>
        <img src="https://i.imgur.com/d1CWqTL.png" alt="crying_paige" class="sad-paige">
    </p>
<% else %>
    <% @current_user.books.each do |book| %>
        <div class="card mt-3" style="max-width: 100%; max-height: 10%;">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <% if book.img_url.nil? %>
                        <img src="https://i.imgur.com/mDC0Ta8.png" class="card-img-top img_book_fit" alt="book_cover">
                    <% else %>
                        <img src="<%= book.img_url %>" class="card-img-top" alt="book_cover">
                    <% end %>
                </div>

                <div class="col-md-9">
                    <div class="card-body">
                        <h3 class="card-title book"><%= link_to book.title, book %></h3>
                        <p><em class="card-text">by <%= book.author_name %></em></p>
                        <p class="card-text"><%= h truncate(book.synopsis_cleansing, :length => 200) %></p>
                        
                        <%= form_tag remove_from_reading_list_path, method: 'delete' do %>
                            <%= hidden_field_tag :search, @search %>
                            <%= hidden_field_tag :book_id, book.id %>
                            <%= hidden_field_tag :author_id, book.author.name %>
                            <% if !book.web_reader_link.empty?%>
                                <%= link_to "Read book", book.web_reader_link, target:"_blank", class:"btn btn-burgundy" %>
                            <% else %>
                                <p class = " btn btn-inactive m-3">Read book</p>
                            <% end %>
                            <%= link_to "Add a review", new_review_path(book_id: book.id), class:"btn btn-primary" %>
                            <%= submit_tag :"Remove from Reading List", class: "btn btn-remove"%>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<h1 class="welcome mt-3">Edit User</h1>
<p class="small-caps">please enter your new settings below:</p>
    <%= form_for @user, html: {:class =>"form-group"} do |f| %>
        <div class="row mt-4">
            <div class="form-group col-6">
                <%= f.label :email_address %>
                <%= f.text_field :email_address, :class =>"form-control mb-2" %>
                <%= f.label :password %>
                <%= f.password_field :password, :class =>"form-control mb-2" %>
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, :class =>"form-control mb-2" %>
                <%= f.submit :"Update password", :class => "btn btn-primary mt-3" %>
            </div>
        </div>
    <% end %>

app/views/users/new.html.erb
<h1 class="m-3 small-caps">Sign up</h1>
  
<div class="container mt-3 ml-0">
    <%= form_for @user, html: {:class =>"form-group"} do |f| %>
        <div class="row">
            <div class="form-group col-4">
                <%= f.label :username %>
                <%= f.text_field :username, :class =>"form-control mb-4" %>
                <%= f.label :email_address %>
                <%= f.text_field :email_address, :class =>"form-control mb-4" %>
                <%= f.label :password %>
                <%= f.password_field :password, :class =>"form-control mb-2" %>
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, :class =>"form-control mb-4" %>
                <%= f.submit :"Create User", :class => "btn btn-primary mt-3" %>
                <%= link_to "Back", login_path, :class => "btn btn-primary mt-3"  %>
            </div>
        </div>
    <% end %>
</div>