config/routes.rb
Rails.application.routes.draw do

  root 'welcome#homepage'
  
  get '/login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update]
  resources :books, only: [:index, :show]
  # resources :authors, only: [:index, :show]
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]

  get '/reading_list', to: 'users#reading_list'
  post '/add_to_reading_list/:id', to: 'books#add_to_reading_list'
  delete '/remove_from_reading_list/:id', to: 'books#remove_from_reading_list'

  get '/search', to: 'books#search'
  post '/add_to_reading_list_via_api', to: 'books#add_to_reading_list_via_api'
  delete '/remove_from_reading_list_via_api', to: 'books#remove_from_reading_list_via_api'
  delete '/remove_from_reading_list', to: 'books#remove_from_reading_list'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  has_many :reviews

  def author_name
    self.author.name
  end

  def genre_name
    self.genre.name
  end

  def average_rating
    if self.reviews.size == 0
      "No ratings yet"
    else
      total_rating = self.reviews.map{|review| review.rating}
      average = total_rating.inject{|sum, el| sum + el}.to_f/total_rating.size
      "User rating: #{average.to_i}/5"
    end
  end

  def star_rating
    if average_rating >= 5
      "*****"
    elsif average_rating >= 4
      "****"
    elsif average_rating 
      "***"
    elsif average_rating 
      "**"
    elsif average_rating 
      "*"
    end
  end

  def synopsis_cleansing
    if self.synopsis.empty?
      "No synopsis available"
    else
      self.synopsis
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :authentication_required, :current_user
    before_action :find_book, only: [:show]

    def index
        @books = Book.all
        @search = ""
    end

    def show
    end

    def search
       @search = params[:q]
       @request = JSON.parse(RestClient.get "https://www.googleapis.com/books/v1/volumes?q=intitle:#{@search}&maxResults=10")["items"]
       render 'index'
    end

    def add_to_reading_list_via_api

        if params["book"]["author"].empty?
            author = Author.find_or_create_by(name: "Anonymous")
        else
            author = Author.find_or_create_by(name: params["book"]["author"])
        end

        if params["book"]["genre"].empty?
            genre = Genre.find_or_create_by(name: "None")
        else
            genre = Genre.find_or_create_by(name: params["book"]["genre"])
        end
        
        book = Book.find_or_create_by(
            title: params["book"]["title"], 
            synopsis: params["book"]["synopsis"],
            published_date: params["book"]["published_date"],
            genre_id: genre.id,
            author_id: author.id,
            img_url: params["book"]["img_url"],
            web_reader_link: params["book"]["web_reader_link"]
        )

        @current_user.books << book

        flash[:notices] = ["Book successfully added to your reading list"]

        @search = (params[:search]).delete('\\"')
        redirect_to "/search?q=#{@search}&commit=Search"
    end

    def remove_from_reading_list_via_api
        ReadingList.find_by(user_id: @current_user.id, book_id: params[:book_id]).destroy
        flash[:notices] = ["Book successfully removed from your reading list"]
        @search = params[:search]
        redirect_to "/search?q=#{@search}&commit=Search"
    end

    def remove_from_reading_list
        ReadingList.find_by(user_id: @current_user.id, book_id: params[:book_id]).destroy
        flash[:notices] = ["Book successfully removed from your reading list"]
        @search = params[:search]
        redirect_to "/reading_list"
    end

    private

    def find_book
        @book = Book.find(params[:id])        
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class = "search-form"> 
  <p class="welcome text-center m-2">Library </p>
  <h1 class="text-center small-caps m-2">find a book:</h1>
  <%= form_tag :"search", method: "get", class: "form-inline pt-2 m-2 my-2 my-lg-0" do %>
    <%= text_field_tag :"q", "", placeholder: "Search", class: "form-control pt-2 mr-sm-2" %>
    <%= submit_tag :"Search", class: "btn btn-primary my-2 my-sm-0"%>
  <% end %>
</div>

<% if @request.nil? && !@search.empty? %>
    <p class="text-center mt-3">
        <em>Hmmm... I can't seem to find "<%= @search %>".</em>
    </p>
    <img src= "https://i.imgur.com/mDC0Ta8.png" class="confused-paige">
<%elsif !@request.nil?%>
  <% @request.each do |book| %>
    <div class="card mt-4" style="max-width: 100%; max-height: 10%;">
      <div class="row no-gutters">
        <div class="col-md-3">
          <% if !book["volumeInfo"]["imageLinks"].present?%>
            <% book_image = "https://i.imgur.com/mDC0Ta8.png" %>
          <% else %>
            <% book_image = book["volumeInfo"]["imageLinks"]["smallThumbnail"] %>
          <% end %>
          <img src=<%= book_image %> class="card-img img_book_fit" alt="book_cover">
        </div>
        <div class="col-md-9">
          <div class="card-body">
            <h5 class="card-title book"><%= title = book["volumeInfo"]["title"] %></h5>
            <p class="card-text">
              <em>
                <% if book["volumeInfo"]["authors"].present? %> 
                  by <%=author = book["volumeInfo"]["authors"].first %>
                <% else %>
                  <%= "No author available" %>
                <% end %>
              </em>
            </p>
            <p class="card-text">
            
            <% if book["volumeInfo"]["description"].present? %>
              <%=synopsis = book["volumeInfo"]["description"].truncate(200)%>
            <%else%>
              <%= "No synopsis available" %>
            <% end %>

            <% if @current_user.book_exist(title, author) %>
              <% existing_book = @current_user.book_exist(title, author) %>
              <%= form_tag remove_from_reading_list_via_api_path, method: 'delete' do %>
                <%= hidden_field_tag :search, @search %>
                <%= hidden_field_tag :book_id, existing_book.id %>
                <%= hidden_field_tag :author_id, existing_book.author.name %>
                <p class = " btn btn-inactive m-3">Add to Reading List</p>
                <%= submit_tag :"Remove from Reading List", class: "btn btn-remove m-3"%>
              <% end %>
            <% else %>
              <%= form_tag add_to_reading_list_via_api_path, method: 'post' do %>
                <%= hidden_field_tag :search, @search %>
                <%= hidden_field_tag :"book[title]", title %>
                <%= hidden_field_tag :"book[synopsis]", book["volumeInfo"]["description"] %>
                <%= hidden_field_tag :"book[published_date]", book["volumeInfo"]["publishedDate"] %>
                <%= hidden_field_tag :"book[genre]", book["volumeInfo"]["categories"] %>
                <%= hidden_field_tag :"book[author]", author %>
                <%= hidden_field_tag :"book[img_url]", book_image %>
                <%= hidden_field_tag :"book[web_reader_link]", book["accessInfo"]["webReaderLink"] %>
                <%= submit_tag :"Add to Reading List", class: "btn btn-primary m-3"%>
                <p class = " btn btn-inactive m-3">Remove from Reading List</p>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <img src= "https://i.imgur.com/mDC0Ta8.png" class="confused-paige">
<% end %>

app/views/books/show.html.erb
<h1 class="mt-3"><%= @book.title %></h1>
<p>
    <em>by <%= @book.author_name %></em> | <%= @book.average_rating %> | Genre: <%= @book.genre_name %>
</p>

<h3 class="mt-4">Synopsis: </h3>
<p class="mt-3"><%= @book.synopsis_cleansing %></p>


<h3 class="mt-4">Reviews:</h3>
<p><%= link_to "Add Review", new_review_path(book_id: @book.id), {class:"btn btn-primary"} %></p>

<% if @book.reviews.count != 0 %>
    <% @book.reviews.each do |review| %>
        <div class="card mb-3">
            <div class="card-header">
                <%= review.username %> - <%= review.rating %>/5
            </div>
            <div class="card-body">
                <p class="card-text">"<%= review.content %>"</p>
                <% if review.user_id == @current_user.id %>
                    <%= link_to "Edit", edit_review_path(id: review.id, book_id: @book.id), {method:'get', class:"btn btn-primary"} %>  
                    <%= link_to "Delete", review_path(id: review.id, book_id: @book.id), {method:'delete', class:"btn btn-danger"} %>  
                <% end %>
            </div>
        </div>
    <% end %>
<% else %>
    <p>No one has left a review yet. Be the first to add one! </p>
<% end %>