config/routes.rb
Rails.application.routes.draw do

  root 'welcome#homepage'
  
  get '/login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update]
  resources :books, only: [:index, :show]
  # resources :authors, only: [:index, :show]
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]

  get '/reading_list', to: 'users#reading_list'
  post '/add_to_reading_list/:id', to: 'books#add_to_reading_list'
  delete '/remove_from_reading_list/:id', to: 'books#remove_from_reading_list'

  get '/search', to: 'books#search'
  post '/add_to_reading_list_via_api', to: 'books#add_to_reading_list_via_api'
  delete '/remove_from_reading_list_via_api', to: 'books#remove_from_reading_list_via_api'
  delete '/remove_from_reading_list', to: 'books#remove_from_reading_list'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :genres, through: :books

    def unique_genre_name
        self.genres.map do |genre|
            genre.name
        end.uniq
    end

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  has_many :reviews

  def author_name
    self.author.name
  end

  def genre_name
    self.genre.name
  end

  def average_rating
    if self.reviews.size == 0
      "No ratings yet"
    else
      total_rating = self.reviews.map{|review| review.rating}
      average = total_rating.inject{|sum, el| sum + el}.to_f/total_rating.size
      "User rating: #{average.to_i}/5"
    end
  end

  def star_rating
    if average_rating >= 5
      "*****"
    elsif average_rating >= 4
      "****"
    elsif average_rating 
      "***"
    elsif average_rating 
      "**"
    elsif average_rating 
      "*"
    end
  end

  def synopsis_cleansing
    if self.synopsis.empty?
      "No synopsis available"
    else
      self.synopsis
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
    has_many :authors, through: :books
end

app/models/reading_list.rb
class ReadingList < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  def username
    self.user.username
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :reading_lists
    has_many :reviews
    has_many :books, through: :reading_lists

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :email_address, presence: true
    validates :email_address, uniqueness: true
    validates :password, presence: true

    def total_books
        self.books.count
    end

    def book_exist(title, author)
        self.books.find do |book|
            book.title == title && book.author.name == author
        end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    before_action :authentication_required, :current_user
    before_action :find_author, only: [:show]

    def index
        @authors = Author.all
    end

    def show
    end

    private

    def find_author
        @author = Author.find(params[:id])        
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :authentication_required, :current_user
    before_action :find_book, only: [:show]

    def index
        @books = Book.all
        @search = ""
    end

    def show
    end

    def search
       @search = params[:q]
       @request = JSON.parse(RestClient.get "https://www.googleapis.com/books/v1/volumes?q=intitle:#{@search}&maxResults=10")["items"]
       render 'index'
    end

    def add_to_reading_list_via_api

        if params["book"]["author"].empty?
            author = Author.find_or_create_by(name: "Anonymous")
        else
            author = Author.find_or_create_by(name: params["book"]["author"])
        end

        if params["book"]["genre"].empty?
            genre = Genre.find_or_create_by(name: "None")
        else
            genre = Genre.find_or_create_by(name: params["book"]["genre"])
        end
        
        book = Book.find_or_create_by(
            title: params["book"]["title"], 
            synopsis: params["book"]["synopsis"],
            published_date: params["book"]["published_date"],
            genre_id: genre.id,
            author_id: author.id,
            img_url: params["book"]["img_url"],
            web_reader_link: params["book"]["web_reader_link"]
        )

        @current_user.books << book

        flash[:notices] = ["Book successfully added to your reading list"]

        @search = (params[:search]).delete('\\"')
        redirect_to "/search?q=#{@search}&commit=Search"
    end

    def remove_from_reading_list_via_api
        ReadingList.find_by(user_id: @current_user.id, book_id: params[:book_id]).destroy
        flash[:notices] = ["Book successfully removed from your reading list"]
        @search = params[:search]
        redirect_to "/search?q=#{@search}&commit=Search"
    end

    def remove_from_reading_list
        ReadingList.find_by(user_id: @current_user.id, book_id: params[:book_id]).destroy
        flash[:notices] = ["Book successfully removed from your reading list"]
        @search = params[:search]
        redirect_to "/reading_list"
    end

    private

    def find_book
        @book = Book.find(params[:id])        
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    before_action :authentication_required, :current_user

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authentication_required, :current_user
    before_action :find_review, only: [:edit, :update]

    def new
        @review = Review.new
        @book = Book.find(params[:book_id])
    end
    
    def create
        review = Review.create(review_params)
        book = Book.find(params[:review][:book_id])
        redirect_to book
    end

    def edit 
        @book = Book.find(params[:book_id])
    end

    def update 
        @review.update(review_params)
        book = Book.find(params[:review][:book_id])
        redirect_to book
    end 

    def destroy
        Review.find(params[:id]).destroy
        book = Book.find(params[:book_id])
        redirect_to book
    end

    private

    def review_params
        params.require(:review).permit(:rating, :content, :user_id, :book_id)
    end

    def find_review 
       @review = Review.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :current_user, except: [:new, :create]
    before_action :find_user, only: [:edit, :update]

    def new
        @user = User.new
    end

    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:errors] = user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit  
        @user = @current_user
    end

    def update
        @user.update(user_params)
        @user.save
        flash[:notices] = ["User updated"]
        redirect_to edit_user_path(@user)
    end

    def reading_list
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email_address, :password, :password_confirmation)
    end

    def find_user
        @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/reading_lists_helper.rb
module ReadingListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Read.it</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://fonts.googleapis.com/css?family=Lobster|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
    <%= favicon_link_tag asset_path('favicon-96x96.png') %>
    <%= favicon_link_tag asset_path('favicon-16x16.png') %>
  </head>

  <body>
  <%# HOME MENU %>
  
    <nav class="navbar navbar-expand-lg">
    <img class = "logo mr-4" src = "https://i.imgur.com/aDPJrpi.png" alt = "Paige Turner" height = 10% width = 10% >
    <ul class="navbar-nav">
        <li class="nav-item mr-3 strapline nav-link">Read.it!</li>
      <% if !@current_user.nil? %>
        <li class="nav-item mt-3 mr-3"><%= link_to "reading list", reading_list_path, class:"nav-link small-caps" %></li>
        <li class="nav-item mt-3 mr-3"><%= link_to "library", books_path, class:"nav-link small-caps" %></li>
        <li class="nav-item mt-3 mr-3"><%= link_to "settings", edit_user_path(@current_user), class:"nav-link small-caps" %></li>
        <li class="nav-item mt-3 mr-3"><%= link_to "log out", logout_path, {method: 'post', class:"nav-link small-caps flex-end"} %></li>
        </ul>
      <% end %>
      
    
  </nav>


  <%# HANDLING ERROR MESSAGES %>
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <div class="container mt-3 ml-0">
      <div class="row">
        <div class="alert alert-danger col0"><%= error %></div>
      </div>
    </div>
    <% end %>
  <% end %>

<%# HANDLING NOTICES MESSAGES %>
  <% if flash[:notices] %>
  <% flash[:notices].each do |notice| %>
  <div class="container mt-3 ml-0">
    <div class="row">
      <div class="alert alert-success col0"><%= notice %></div>
    </div>
  </div>
  <% end %>
<% end %>
  
    <%= yield %>

  </body>


</html>